version: '3'

services:
  PostgreSQL:
    container_name: 'postgres-${CONTAINER_SUFFIX}'
    image: postgres:10-alpine
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file: deploy/env/PostgreSQL.env
    volumes:
      - ~/docker-volumes/postgresql:/var/lib/postgresql/data

  foosball-rating-backend:
    container_name: 'foosball-rating-backend-${CONTAINER_SUFFIX}'
    build: .
    restart: always
    env_file: deploy/env/backend.env
    depends_on:
      - 'PostgreSQL'

  foosball-rating-frontend:
    container_name: 'foosball-rating-frontend-${CONTAINER_SUFFIX}'
    build: frontend
    restart: always
    env_file: deploy/env/frontend.env

networks:
  default:
    external:
      name: nginx-proxy
