version: '3'

services:
  PostgreSQL:
    container_name: 'postgres-${CONTAINER_SUFFIX}'
    image: postgres:10-alpine
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file: deploy/env/PostgreSQL.env
    volumes:
      - ~/docker-volumes/postgresql:/var/lib/postgresql/data

  foosball-rating-backend:
    container_name: 'foosball-rating-backend-${CONTAINER_SUFFIX}'
    image: 192.168.0.32:50000/foosball-rating/backend:${BUILD}
    restart: always
    env_file: deploy/env/backend.env
    volumes:
      - ./.env:/app/.env
      - ./ormconfig.json:/app/ormconfig.json
      - ./deploy/env/secrets.env:/app/deploy/env/secrets.env
    depends_on:
      - 'PostgreSQL'

  foosball-rating-frontend:
    container_name: 'foosball-rating-frontend-${CONTAINER_SUFFIX}'
    image: 192.168.0.32:50000/foosball-rating/frontend:${BUILD}
    restart: always
    env_file: deploy/env/frontend.env

networks:
  default:
    external:
      name: nginx-proxy
