version: '2'

services:
  PostgreSQL:
    container_name: psql
    image: postgres:10-alpine
    ports:
      - '9219:5432'
    environment:
      - POSTGRES_USER=zero
      - POSTGRES_PASSWORD=zero
      - POSTGRES_DB=foosball-rating
      - PGDATA=/var/lib/postgresql/data/db-files/
    volumes:
      - ./docker-volumes/postgresql:/var/lib/postgresql/data
    networks:
      - foosball-rating-net

  foosball-rating-backend:
    container_name: foosball-rating-backend
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - 'PostgreSQL'
    networks:
      - foosball-rating-net

  foosball-rating-frontend:
    container_name: foosball-rating-frontend
    build: frontend
    restart: always
    ports:
      - '5000:5000'
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    networks:
      - foosball-rating-net

networks:
  foosball-rating-net:
    external: true
